import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import { Cursor } from "@/components/Cursor";

const tungstenBold = localFont({
  src: "./fonts/Tungsten-Bold.woff",
  variable: "--tungsten-bold",
  weight: "700",
});

const tungstenSemiBold = localFont({
  src: "./fonts/Tungsten-Semibold.woff",
  variable: "--tungsten-semi-bold",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tungstenBold.className} ${tungstenSemiBold.className}`}>
        <ThemeWrapper>{children}</ThemeWrapper>
        <Cursor />
      </body>
    </html>
  );
}
